version: "2"
services:
  node:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
      - "3001:3001"
    expose:
      - "8081"
    command: "node index.js"